# See: https://talk.openmrs.org/t/installing-bahmni-with-limited-internet/5392

# The below should have been created during the enable-yum-caching task, but check just in case

- name: Check whether yum caching has run for the first time
  stat: path=/etc/yum_cache/opt_rpms
  register: yum_cache_rpms_folder

- name: Copy anything that exists in /opt into /etc/yum_cache/opt_rpms (this is needed for java download for example)
  shell: cp /opt/* /etc/yum_cache/opt_rpms
  when: yum_cache_rpms_folder.stat.isdir is defined and yum_cache_rpms_folder.stat.isdir
  ignore_errors: yes