# Remove any existing bahmni-installer package

- name: Remove the existing bahmni-installer rpm
  shell: yum remove -y bahmni-installer

- name: Remove the existing bahmni-installer directory
  command: rm -rf /etc/bahmni-installer

# Ensure that the specified version of the bahmni installer package is installed

- name: Install bahmni-installer version {{ bahmni_version }}
  shell: yum install -y {{ bahmni_installer_url }}

# Add new installer files where Bahmni needs to be patched

- name: "Add alternative oracle-java.yml file"
  copy: src=oracle-java.yml
    dest=/opt/bahmni-installer/bahmni-playbooks/roles/oracle-java/tasks
    mode=755
    owner={{ bahmni_user }}
    group={{ bahmni_group }}