# Ensure that the specified version of the bahmni installer package is installed

- name: Check the version of any existing bahmni-installer rpm
  command: yum list installed bahmni-installer
  register: existing_bahmni_installer_version  
  ignore_errors: yes

- include: remove-installer.yml
  when: existing_bahmni_installer_version.stdout.find("{{ bahmni_version }}") == -1

- name: Install bahmni-installer version {{ bahmni_version }}
  yum: name="{{ bahmni_installer_url }}" state=present

# For some reason, as of Feb 2, 2017 ansible installation does not seem to have taken place
# Explicitly do this again here

- include: install-ansible.yml
