# Deploy custom build of bahmniapps

- name: Download bahmniapps from remote location as zip file
  get_url: url={{ bahmniapps_zip_url }} dest={{ bahmni_deployment_artifacts }}/bahmniapps.zip
  when: bahmniapps_zip_url is defined

- stat: path={{ bahmni_deployment_artifacts }}/bahmniapps.zip
  register: bahmniapps_zip

- name: Clear out existing bahmniapps content
  command: "rm -fR /opt/bahmni-web/etc/bahmniapps/*"
  when: bahmniapps_zip.stat.exists == True

- name: Extract contents of zip file into bahmniapps directory
  unarchive: src={{ bahmni_deployment_artifacts }}/bahmniapps.zip dest=/opt/bahmni-web/etc/bahmniapps/ copy=no
  when: bahmniapps_zip.stat.exists == True

- name: Set permissions on bahmniapps dir
  file: path=/opt/bahmni-web/etc/bahmniapps owner=bahmni group=bahmni mode=0755 recurse=yes

- name: Remove downloaded zip file
  file: path={{ bahmni_deployment_artifacts }}/bahmniapps.zip state=absent