
- name: Download bahmniendtb from remote location
  shell: wget -P {{ openmrs_data_directory }}/modules/ -O {{ bahmniendtb_omod_target_name }} {{ bahmniendtb_omod_url }}
  when: bahmniendtb_omod_url is defined
  register: bahmniendtb_installed

- name: Restart OpenMRS
  service: name=openmrs state=restarted
  when: bahmniendtb_installed.changed
