# See: https://talk.openmrs.org/t/installing-bahmni-with-limited-internet/5392

- name: Create yum cache folder, and subfolder for storing additional cache artifacts from the opt folde
  file: path=/etc/yum_cache/opt_rpms/ state=directory

- name: Enable caching of yum repositories
  command: sed -i "s|keepcache=0|keepcache=1|g" /etc/yum.conf

- name: Set yum cache folder to the one created above
  command: sed -i "s|cachedir=/var/cache/yum/\$basearch/\$releasever|cachedir=/etc/yum_cache|g" /etc/yum.conf

- name: Copy anything that exists in opt_rpms into /opt (this is needed for using previously cached java download for example)
  shell: cp /etc/yum_cache/opt_rpms/* /opt
  ignore_errors: yes