
# Add the necessary inventory and setup.yml files needed by the bahmni installer

- name: Add setup.yml
  template: src=setup.yml.j2 dest={{ bahmni_installer_directory }}/setup.yml

- name: Add inventory file
  copy: src=emr-inventory dest={{ bahmni_installer_directory }}/inventory

# Yum clean

- name: Yum clean
  command: yum clean all

###### start temporary patch

# This will not be needed in the future, but for now release-0.86 does not support configuring SSL certificate paths
# Once it does, we can remove this and do it via configuration in setup.yml.j2

- include: patch-ssl.yml
  when: ssl_certificate_file_path is defined

###### end temporary patch

# Run the bahmni installer from the {{ bahmni_installer_directory }} directory

- name: Run the bahmni installer
  shell: bahmni -i inventory install
  args:
    chdir: "{{ bahmni_installer_directory }}"
    executable: /bin/bash

# Run the endtb custom playbooks

- name: Run the endtb_config playbooks
  shell: bahmni --implementation_play=/var/www/bahmni_config/playbooks/all.yml -i inventory install-impl
  args:
    chdir: "{{ bahmni_installer_directory }}"
    executable: /bin/bash

###### Performance patch for bahmniapps 0.86.  See: https://tickets.pih-emr.org/browse/ED-21

# This step can likely be removed if we fork and customize bahmniapps on our own, or upgrade to a later version of Bahmni

- name: Execute the PerformanceFix_PatientSummary.sh patch
  script: "{{ role_path }}/files/PerformanceFix_PatientSummary.sh"

###### end peformance patch