- name: Download initializer from remote location
  get_url: url={{ initializer_url }} dest=/opt/openmrs/modules owner={{ bahmni_user }} group={{ bahmni_group }}
  when: initializer_url is defined

- name: Remove configuration folder if exists
  command: rm -rf /opt/openmrs/configuration/
  ignore_errors: true

- name: Create Initializer configuration directory
  file: path="/opt/openmrs/configuration" state=directory owner={{ bahmni_user }} group={{ bahmni_group }}

- name: Remove configuration folder if exisits
  command: rm -rf /tmp/package
  ignore_errors: true

- name: Download form package
  git: repo={{ package_url }} dest=/tmp/package

- name: Move concepts folder to /opt/configuration
  command: mv /tmp/package/concepts /opt/openmrs/configuration/

- name: Move scripts folder to /opt/configuration
  command: mv /tmp/package/scripts /opt/openmrs/configuration/

- name: Install exports crontab job
  cron: name={{ exports_cron }} job="/usr/bin/bahmni-batch belongs_to_external_cohort={{ job_name }}" user={{ bahmni_user }} state=present hour={{ cron_hour }} minute={{ cron_minutes }}