
# Add the necessary inventory and setup.yml files needed by the bahmni installer

- name: Add setup.yml
  template: src=setup.yml.j2 dest={{ bahmni_installer_directory }}/setup.yml

- name: Add inventory file
  copy: src=emr-inventory dest={{ bahmni_installer_directory }}/inventory

# Yum clean

- name: Yum clean
  command: yum clean all

# Run the bahmni installer from the {{ bahmni_installer_directory }} directory

- name: Run the bahmni installer
  shell: bahmni -i inventory -av 2.2.0.0 install
  args:
    chdir: "{{ bahmni_installer_directory }}"
    executable: /bin/bash

# Run the endtb custom playbooks

- name: Run the endtb_config playbooks
  shell: bahmni --implementation_play=/var/www/bahmni_config/playbooks/all.yml -i inventory install-impl
  args:
    chdir: "{{ bahmni_installer_directory }}"
    executable: /bin/bash
