# Install Bahmni

- include: enable-yum-caching.yml
- include: add-package-dependencies.yml
- include: add-installer.yml
- include: add-implementation-config.yml
- include: install-bahmni.yml
- include: run-bahmni-batch.yml
