# Install Bahmni

- include: enable-yum-caching.yml
- include: add-package-dependencies.yml
- include: add-installer.yml
- include: add-endtb-config.yml
- include: install-bahmni.yml
- include: run-bahmni-batch.yml
- include: add-additional-cache-artifacts.yml
- include: deploy-implementation-config.yml
- include: deploy-bahmniendtb.yml
- include: customize-report-names.yml