
# This will not be needed in the future, but for now release-0.86 does not support configuring SSL certificate paths
# Once it does, we can remove this and do it via configuration in setup.yml.j2

- name: Patch SSLCertificateFile
  replace:
    dest: /opt/bahmni-installer/bahmni-playbooks/roles/bahmni-web/templates/ssl.conf.j2
    regexp: "SSLCertificateFile \/etc\/bahmni-certs\/cert\.crt"
    replace: "SSLCertificateFile {{ ssl_certificate_file_path }}"
    backup: yes

- name: Patch SSLCertificateKeyFile
  replace:
    dest: /opt/bahmni-installer/bahmni-playbooks/roles/bahmni-web/templates/ssl.conf.j2
    regexp: "SSLCertificateKeyFile \/etc\/bahmni-certs\/domain\.key"
    replace: "SSLCertificateKeyFile {{ ssl_certificate_key_file_path }}"
    backup: yes

- name: SSLCertificateChainFile
  replace:
    dest: /opt/bahmni-installer/bahmni-playbooks/roles/bahmni-web/templates/ssl.conf.j2
    regexp: "SSLCertificateChainFile \/etc\/bahmni-certs\/chained\.pem"
    replace: "SSLCertificateChainFile {{ ssl_certificate_chains_file_path }}"
    backup: yes
