# Bahmni version to install.  Used by add-installer task

bahmni_version: "0.88-101"
bahmni_repo_url: "http://dl.bintray.com/bahmni/rpm"
bahmni_installer_url: "{{ bahmni_repo_url }}/rpms/bahmni-installer-{{ bahmni_version }}.noarch.rpm"

# Customizations to install - endtb_config and custom omods

endtb_config_url: "https://github.com/endtb/endtb-config/archive/master.zip"
bahmniapps_zip_url: "http://bamboo.pih-emr.org/bahmni-repo/endtb-bahmniapps-0.88-latest.zip"

# These should be set with implementation-specific config for a particular country
# implementation_config_zip_url: ""
# implementation_config_subdirectory: ""

bahmni_installer_directory: "/etc/bahmni-installer"
bahmni_deployment_artifacts: "{{ bahmni_installer_directory }}/deployment-artifacts"
omods: ["https://dl.bintray.com/endtb/snapshots/bahmniendtb-1.8-SNAPSHOT.omod", "https://dl.bintray.com/endtb/snapshots/dataintegrity-omod-4.2.3.omod"]

# Expected to be overridden for a particular environment (eg. production, test)
# For all options, see https://bahmni.atlassian.net/wiki/display/BAH/List+Of+Configurable+Installation+Variables
# Anything added here also needs to be added to the setup.yml.j2 file under templates

timezone: "America/New_York"
selinux_state: "permissive"
openmrs_server_options: "-Xms1024m -Xmx2048m -XX:PermSize=512m -XX:MaxPermSize=1024m"

openmrs_user_password: "Admin123"
openmrs_db_password: "openmrs"
mysql_root_password: "root"
