# Bahmni version to install.  Used by add-installer task

bahmni_version: "0.88-101"
bahmni_repo_url: "http://dl.bintray.com/bahmni/rpm"
bahmni_installer_url: "{{ bahmni_repo_url }}/rpms/bahmni-installer-{{ bahmni_version }}.noarch.rpm"

# Customizations to install - endtb_config and custom omods

endtb_config_url: "https://github.com/endtb/endtb-config/archive/master.zip"

# TODO replace this once we fix our build pipeline to actually deploy the omod to some place we can properly grab it from
# this is used to deploy the latest build of our custom version of bahmniapps from our build pipeline; during a release
#bahmniendtb_omod_url: "https://openmrs.jfrog.io/openmrs/public/org/bahmni/module/bahmniendtb-omod/2.1.0-SNAPSHOT/bahmniendtb-omod-2.1.0-SNAPSHOT.jar"
#bahmniendtb_omod_target_name: "bahmniendtb-2.1.0-SNAPSHOT.omod"
#openmrs_data_directory: "/opt/openmrs"


# These should be set with implementation-specific config for a particular country
# implementation_config_zip_url: "https://github.com/PIH/pih-bahmni-config/archive/master.zip"
# implementation_config_subdirectory: "pih-bahmni-config-master/endTB-implementation-config/peru_implementation_config"

bahmni_installer_directory: "/etc/bahmni-installer"
bahmni_deployment_artifacts: "{{ bahmni_installer_directory }}/deployment-artifacts"
omods: [ "https://github.com/endtb/openmrs-module-bahmniendtb/releases/download/2.1.0/bahmniendtb-2.1.0.omod", "https://modules.openmrs.org/modulus/api/releases/1545/download/dataintegrity-4.2.3.omod", "https://s3.amazonaws.com/endtb-artifacts/1.6/bahmnicore-omod-0.88-SNAPSHOT.omod", "https://s3.amazonaws.com/endtb-artifacts/1.1/bacteriology-1.1-SNAPSHOT.omod"]


# Expected to be overridden for a particular environment (eg. production, test)
# For all options, see https://bahmni.atlassian.net/wiki/display/BAH/List+Of+Configurable+Installation+Variables
# Anything added here also needs to be added to the setup.yml.j2 file under templates

timezone: "America/New_York"
selinux_state: "permissive"
openmrs_server_options: "-Xms1024m -Xmx2048m -XX:PermSize=512m -XX:MaxPermSize=1024m"

openmrs_user_password: "Admin123"
openmrs_db_password: "openmrs"
mysql_root_password: "root"
