# This playbook serves to setup a new bahmni server

- hosts: all
  become: yes
  gather_facts: false  
  vars:
    initializer_url: "https://bamboo.pih-emr.org:81/endtb/modules/initializer-1.1.0.omod"
    stemtb_repo_url: "https://github.com/endtb/stem-tb.git"
    package_url: "https://github.com/endtb/package1.git" 
    bahmni_user: "bahmni"
    bahmni_group: "bahmni"
    exports_cron: "Stem TB exports"
    job_name: "stemTB"
    cron_hour: 00
    cron_minutes: 02
  tasks: 
  - include_tasks: roles/bahmni/tasks/install-form-packages.yml
  - include_tasks: roles/bahmni/tasks/add-package1-configurations.yml
